### ISSUE TITLE
Set ARTIFACT_BASENAME and RELEASE_BASENAME

### ISSUE THREAD

**Issue by brummer10** [DISTRHO/dpf-makefile-action#2]
Hi
I try to find a way to add a postfix to the ARTIFACT_BASENAME and RELEASE_BASENAME.
Reason is that I would like to provide optimised builds using  the -march=x86-64-v3. This is only possible when using ubuntu-22.04 (latest). So I like to provide builds for ubuntu-20.04 (for older distributions) and as well optimised builds for ubuntu-latest, in separate packages. Unfortunately they comes out with the same ARTIFACT_BASENAME and RELEASE_BASENAME so they overwrite the previous build and only one of the left.  
Only way I found was to use different bin/bundle names which result with a artifact contain both binary versions. 
So I wonder if there is a way to add a postfix to the ARTIFACT_BASENAME and RELEASE_BASENAME so that they comes out as separate packages?
Maybe something like a env var which could as well be used to provide separate packages for the different plugin types?

regards
hermann

**Comment by brummer10** [comment]
I did a quick test with a forked version adding a postfix var, that does what I need.
https://github.com/brummer10/Ratatouille.lv2/blob/main/.github/actions/action.yml#L38

**Comment by falkTX** [comment]
Fixed in 3b4a4d0f098b4dab74270b4faa885526839f9e33

Note that I updated the sub-actions to github v4 API, as v3 was deprecated.
Ubuntu 18.04 no longer works and artifacts will fail to upload if there are filename conflicts like what you describe.
There might be other github changes, best to try and see if things still build, and report issues as you see them
